# Generated by Django 4.1 on 2024-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="media/profile_imgs/blank-profile.png",
                upload_to="media/profile_imgs",
            ),
        ),
    ]
