# Generated by Django 4.1 on 2024-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_message_id_message_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="level",
            field=models.TextField(default="normal"),
        ),
    ]
