# Generated by Django 4.1 on 2024-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_permission_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="level",
            field=models.TextField(blank=True, default="normal"),
        ),
    ]
