# Generated by Django 4.1 on 2024-01-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_permission_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="open",
            field=models.CharField(default="yes", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="media/profile_imgs/blank.png", upload_to="media/profile_imgs"
            ),
        ),
    ]
